### 뿌리기
POST http://localhost:8080/api/v1/money/share
X-ROOM-ID: 123
X-USER-ID: 1
Content-Type: application/json

{
   "sharingMoney": 10000,
   "targetSize": 10
}

### 조회하기
GET http://localhost:8080/api/v1/status/55m
X-ROOM-ID: 123
X-USER-ID: 1
Content-Type: application/json

### 자기 금액 받아오기
GET http://localhost:8080/api/v1/money/55m
X-ROOM-ID: 123
X-USER-ID: 3
Content-Type: application/json


